version: '3.9'
services:
  postgres:
    container_name: biblioteca-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: process.env.POSTGRES_USER
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
      POSTGRES_DB: process.env.POSTGRES_DB
    ports:
      - 5432:process.env.POSTGRES_PORT
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
